<main id="category" class="py-5 px-3">
    <h1 class="mb-5">Secured Blog</h1>

    <h2 class="mt-5">Category Name</h2>
    <ul class="row mt-5">
        <?php
        foreach($data["posts"] as $post)//pour chaque post de la categorie
        {
        ?>
        
            <li class="col-4 my-2">
                <article class="card">
                    <header class="card-body">
                        <!--on dynamise le html avec le titre du post-->
                        <h3 class="h5 card-title"><?= $post->getTitle() ?></h3>
                    </header>
                    <section class="card-body">
                        <!--on dynamise avec l'excerpt du post recup par son id-->
                        <p class="card-text"><?= $post->getExcerpt()?></p>
                        <!-- on met la ref de la route=post&post_id pour atterir sur le post en question-->
                        <a href="index.php?route=post&post_id=<?= $post->getId() ?>" class="btn btn-primary">Read the post</a>
                    </section>
                </article>
            </li>
        <?php
        }
        ?>
    </ul>
</main>