<main id="login" class="container py-5 px-3">
    <?php // on verifie qu'il y a bien une session valide pour afficher la page
    if(isset($_SESSION["error-message"]))
    {
        ?>
        <!--si message d'erreur session message d'alert et cloture page-->
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <?= $_SESSION["error-message"] ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        <?php
    } 
    ?>
    <h1 class="mb-5">Secured Blog</h1>

    <h2 class="mt-5">Login</h2>

    <form action="index.php?route=check-login" method="post">
        <!-- on insere un champ caché type hidden qui envoie le token pour verif auth à cahque envoi du formulaire -->
        <input type="hidden" name="csrf-token" id="csrf-token" value="<?= $_SESSION["csrf-token"] ?>" />
        <fieldset class="my-1">
            <label for="email" class="form-label">
                Email
            </label>
            <input type="email" name="email" id="email" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="password" class="form-label">
                Password
            </label>
            <input type="password" name="password" id="password" class="form-control" />
        </fieldset>
        <fieldset>
            <button type="submit" class="btn btn-primary">Login</button>
        </fieldset>
    </form>
</main>