<main id="post" class="container py-5 px-3">
    <h1 class="mb-5 text-center">Secure Blog</h1>
    <!--qd on est connecte on accede à la page post avec son titre son content ses comments-->
    <h2 class="mt-5 text-center"><?= $data["post"]->getTitle(); ?></h2>
    <article class="py-5">
        <?= $data["post"]->getContent(); ?>
    </article>
    <section class="my-3">
        <h3>Comments</h3>
        <ul class="list-group mt-4">
            <?php
                foreach($data["comments"] as $comment)
                //pour chaque commentaire on recup contenu et autheur=utilisateur
                {
                    ?>
                <li class="list-group-item">
                    <article>
                        <h4><?= $comment->getUser()->getUsername(); ?></h4>
                        <p>
                            <?= $comment->getContent(); ?>
                        </p>
                    </article>
                </li>
            <?php
                }
            ?>
        </ul>
        <?php  //si on a bien une session user valide on peut poster des commentaires
        if(isset($_SESSION["user"]))
        {
            ?>
            <form action="index.php?route=check-comment" method="post">
                <!--on insere un champ cache qui envoi le token pour auth à chaque envoi du formulaire-->
                <input type="hidden" name="csrf-token" id="csrf-token" value="<?= $_SESSION["csrf-token"] ?>" />
                <!--on rentre automatiquement l'id du post en champ cache-->
                <input type="hidden" name="post-id" id="post-id" value="<?= $data["post"]->getId() ?>" />
                <fieldset class="my-1"> <!--son contenu-->
                    <label for="content" class="form-label">
                        Comment
                    </label>
                    <textarea name="content" id="content" class="form-control">
                </textarea>
                </fieldset>
                <fieldset>
                    <button type="submit" class="btn btn-primary">Send</button>
                </fieldset>
            </form>
        <?php
        }
        else 
        {
        ?>
        <p>Un utilisateur non enregistre ne peut pas faire de commentaire</p>
        <?php
        }
        ?>
    </section>
</main>